name: Deploy to Test VM

on:
  push:
    branches:
      - test  # Change this if you want another branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test  # This links to your GitHub 'test' environment

    env:
      DEPLOY_DIR: /

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            set -e
            cd $DEPLOY_DIR

            # If first time, clone repo
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }} .
            fi

            git pull origin main

            # run post-deploy script if present
            #if [ -f deploy.sh ]; then
              #chmod +x deploy.sh
              #./deploy.sh
            #fi
          EOF
