name: Deploy to Test VM

on:
  push:
    branches:
      - test  # Change this if you want another branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test  # This links to your GitHub 'test' environment

    env:
      DEPLOY_DIR: /app/program/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          set -e
          DEPLOY_DIR="${{ env.DEPLOY_DIR }}"
          cd "$DEPLOY_DIR"
          echo "Changed directory to $DEPLOY_DIR"
          if [ ! -d ".git" ]; then
            echo "Git directory not found, cloning repository..."
            git clone git@github.com:${{ github.repository }} .
            echo "Clone complete."
          else
            echo "Git directory found."
          fi
          
          echo "Fetching origin..."
          git fetch origin
          echo "Checking out branch test..."
          git checkout test || git checkout -b test origin/test
          echo "Pulling latest changes..."
          git pull origin test
          echo "Update complete."
            # post-deploy script once applicable
            #if [ -f deploy.sh ]; then
              #chmod +x deploy.sh
              #./deploy.sh
            #fi
          EOF
