name: Deploy to Test VM

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test

    env:
      DEPLOY_DIR: /app/program/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Code to VM
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} bash -s << 'EOF'
          set -e
          cd "${DEPLOY_DIR}"
          echo "Resetting any local changes..."
          git reset --hard
          git clean -fd
          echo "Killing existing web server if running..."
          pkill -f "python3 web.py" || true
          echo "Pulling latest code..."
          git fetch origin
          git checkout test || git checkout -b test origin/test
          git pull origin test
          echo "Starting web server..."
          nohup python3 web.py > webserver.log 2>&1 &
          echo "Code pulled successfully."
          EOF
